const express = require('express');
const cors = require('cors');
const ServerlessHttp = require('serverless-http');
const app = express();
app.use(cors());

//Deck of Sixty API
//Version 1.2
//Change Notes: Updated some of the meanings for the minor arcana cards

const cards = [
  /* CROWNS (Lightning - Highborn - Domination) */
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 1,
    "name": "First Crown: The Spark",
    "progression": "Mortal",
    "represents": "Inspiration",
    "astral": "A sudden bolt of genius; the drive to lead or innovate.",
    "umbral": "Erratic energy; destructive impulses that lack a target."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 2,
    "name": "Second Crown: The Rivalry",
    "progression": "Mortal",
    "represents": "Competition",
    "astral": "Healthy ambition; rising to meet a peer's challenge.",
    "umbral": "Petty jealousy; being blinded by a desire to surpass others."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 3,
    "name": "Third Crown: The Law",
    "progression": "Mortal",
    "represents": "Social Order",
    "astral": "The establishment of just rules; merit-based success.",
    "umbral": "Tyranny; using one's position to suppress the potential of others."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 4,
    "name": "Fourth Crown: The Manor",
    "progression": "Mortal",
    "represents": "Status",
    "astral": "True nobility; the security of a well-earned reputation.",
    "umbral": "Elitism; hiding behind titles while ignoring actual duty."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 5,
    "name": "Fifth Crown: The Strike",
    "progression": "Mortal",
    "represents": "Sudden Fall",
    "astral": "Necessary disruption; toppling a corrupt structure to rebuild.",
    "umbral": "Disgrace; a public fall from power caused by hubris."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 6,
    "name": "Sixth Crown: The Sovereignty",
    "progression": "Mortal",
    "represents": "Grace",
    "astral": "The peak of leadership; ruling with wisdom and quiet power.",
    "umbral": "The King of Ashes; holding power over a ruined or empty life."
  },
  { "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 7,
    "name": "Knight of Crowns: The Page",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Initiate",
    "astral": "Diligent study of power; learning when to act and when to wait.",
    "umbral": "Entitled youth; seeking the rewards of rank without the effort."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 8,
    "name": "Lord of Crowns: The Count",
    "role": "The Pillar",
    "progression": "Social",
    "represents":
    "Active Authority",
    "astral": "Decisive action; the firm hand that maintains peace and justice.",
    "umbral": "The Despot; a leader who rules through fear and Levinbolts."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 9,
    "name": "Lady of Crowns: The Duchess",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Internal Wisdom",
    "astral": "Refined diplomacy; the 'steel in the velvet' approach.",
    "umbral": "The Puppeteer; manipulation behind a mask of poise."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Domination",
    "class": "The Highborn",
    "rank": 10,
    "name": "The Spire",
    "progression": "Divine",
    "partner_deities": ["Byregot","Rhalgr"],
    "represents": "Purification",
    "astral": "Byregot's Touch: Sudden architectural genius; a path forward where none existed; inspiration to build or repair.",
    "umbral": "Rhalgr's Wrath: The destruction of the old; the cleansing fire of a storm, making way for the new."
  },

  /* SWORDS (Wind - Vanguard - Cognition) */
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 1,
    "name": "First Sword: The Breeze",
    "progression": "Mortal",
    "represents": "Mental Spark",
    "astral": "A fresh perspective; clarity of thought and swift decision-making.",
    "umbral": "Scattered thoughts; mental chaos; lack of direction."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 2,
    "name": "Second Sword: The Scout",
    "progression": "Mortal",
    "represents": "Surveillance",
    "astral": "Preparedness; gathering information before making a move.",
    "umbral": "Indecision; being paralyzed by having too many options."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 3,
    "name": "Third Sword: The Formation",
    "progression": "Mortal",
    "represents": "Strategy",
    "astral": "Mental discipline; organizing one's life for maximum efficiency.",
    "umbral": "Rigidity; being unable to adapt to shifting winds."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 4,
    "name": "Fourth Sword: The Encampment",
    "progression": "Mortal",
    "represents": "Rest",
    "astral": "Necessary mental pause; contemplation before a great effort.",
    "umbral": "Mental stagnation; avoiding conflict through apathy."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 5,
    "name": "Fifth Sword: The Skirmish",
    "progression": "Mortal",
    "represents": "Conflict",
    "astral": "A clash of ideas that leads to a better truth.",
    "umbral": "Discord; a mental or social battle where no one truly wins."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 6,
    "name": "Sixth Sword: The Victory",
    "progression": "Mortal",
    "represents": "Success",
    "astral": "The triumph of logic and skill; achieving a long-term goal.",
    "umbral": "Empty success; a win that leaves one isolated or hated."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 7,
    "name": "Knight of Swords: The Ranger",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Scout",
    "astral": "Relentless curiosity; the one who explores the unknown first.",
    "umbral": "Recklessness; wandering without a map or purpose."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 8,
    "name": "Lord of Swords: The Captain",
    "role": "The Pillar",
    "progression": "Social",
    "represents": "Martial Command",
    "astral": "Bravery; the courage to stand by one's convictions.",
    "umbral": "Brutality; forcing one's will on others through mental or physical force."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 9,
    "name": "Lady of Swords: The Strategist",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Tactical Wisdom",
    "astral": "Foresight; seeing the 'long game' and guiding others toward it.",
    "umbral": "Treachery; using brilliant intellect for selfish or harmful ends."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Cognition",
    "class": "The Vanguard",
    "rank": 10,
    "name": "The Arrow",
    "progression": "Divine",
    "partner_deities": ["Oschon", "Llymlaen"],
    "represents": "Destiny",
    "astral": "Oschon's Way: Finding your true path; the joy of movement and freedom.",
    "umbral": "Llymlaen's Tide: The relentless tide; the hard discipline of staying the course."
  },

  /* VESSELS (Water - Scholars - Emotion) */
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 1,
    "name": "First Vessel: The Drop",
    "progression": "Mortal",
    "represents": "Intuition",
    "astral": "The birth of a feeling; a true spiritual or emotional hunch.",
    "umbral": "Emotional overwhelm; a leak of energy without a container."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 2,
    "name": "Second Vessel: The Confluence",
    "progression": "Mortal",
    "represents": "Empathy",
    "astral": "Deep connection; two souls sharing a single memory.",
    "umbral": "Projection; confusing your own feelings with those of another."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 3,
    "name": "Third Vessel: The Wellspring",
    "progression": "Mortal",
    "represents": "Creativity",
    "astral": "Abundant expression; sharing wisdom with those who thirst.",
    "umbral": "Guardedness; hoarding knowledge or emotions out of fear."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 4,
    "name": "Fourth Vessel: The Basin",
    "progression": "Mortal",
    "represents": "Meditation",
    "astral": "The stillness of the mind; emotional clarity and peace.",
    "umbral": "Stagnation; being caught in a loop of past regrets."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 5,
    "name": "Fifth Vessel: The Overflow",
    "progression": "Mortal",
    "represents": "Release",
    "astral": "A necessary cry; purging old grief to find a fresh flow.",
    "umbral": "Drowning; losing oneself in an ocean of sadness or chaos."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 6,
    "name": "Sixth Vessel: The Sea",
    "progression": "Mortal",
    "represents": "Connection",
    "astral": "Mastery over memory; the realization that all are one.",
    "umbral": "Drifting; losing your individual purpose in the 'wider world'."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 7,
    "name": "Knight of Vessels: The Acolyte",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Student",
    "astral": "Curiosity; seeking a teacher or a new spiritual path.",
    "umbral": "Confusion; studying too much without actually feeling the truth."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 8,
    "name": "Lord of Vessels: The Archon",
    "role": "The Pillar",
    "progression": "Social",
    "represents": "Intellectual Mastery",
    "astral": "Objective truth; the ability to explain the world's mysteries.",
    "umbral": "Arrogance; believing that data is the same as experience."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 9,
    "name": "Lady of Vessels: The Oracle",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Intuitive Mastery",
    "astral": "Enlightenment; acting as a bridge for others' understanding.",
    "umbral": "Delusion; getting lost in your own psychic or emotional visions."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Emotion",
    "class": "The Scholars",
    "rank": 10,
    "name": "The Ewer",
    "progression": "Divine",
    "partner_deities": ["Thaliak", "Nymeia"],
    "represents": "Continuity",
    "astral": "Thaliak's Stream: The flow of the river of knowledge; clarity and logical growth; the active pursuit of wisdom.",
    "umbral": "Nymeia's Thread: The Spinner's fate; accepting things that are beyond control; the passive mysterious influence of the celestial."
  },

  /* STAVES (Earth - Harvesters - Possession) */
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 1,
    "name": "First Staff: The Seed",
    "progression": "Mortal",
    "represents": "Potential",
    "astral": "The start of a physical goal; the raw material for a legacy.",
    "umbral": "Waste; a resource that is ignored or left to rot."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 2,
    "name": "Second Staff: The Sapling",
    "progression": "Mortal",
    "represents": "Flexibility",
    "astral": "Adapting your foundations as you grow; resilience.",
    "umbral": "Fragility; being easily broken by the winds of change."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 3,
    "name": "Third Staff: The Roots",
    "progression": "Mortal",
    "represents": "Foundation",
    "astral": "Stability; building a life that can withstand anything.",
    "umbral": "Stubbornness; being so deeply rooted you cannot move when needed."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 4,
    "name": "Fourth Staff: The Fence",
    "progression": "Mortal",
    "represents": "Boundaries",
    "astral": "Protecting what is yours; healthy limits for yourself and others.",
    "umbral": "Exclusion; building walls that prevent growth or community."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 5,
    "name": "Fifth Staff: The Blight",
    "progression": "Mortal",
    "represents": "Trial",
    "astral": "Survival through scarcity; finding strength in lack.",
    "umbral": "Decay; the physical or spiritual rot of a life or project."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 6,
    "name": "Sixth Staff: The Harvest",
    "progression": "Mortal",
    "represents": "Abundance",
    "astral": "The reward for labor; a legacy that feeds many.",
    "umbral": "Exploitation; taking more from the land or people than you give."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 7,
    "name": "Knight of Staves: The Gatherer",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Laborer",
    "astral": "Hard work; the joy of simple tasks and being in nature.",
    "umbral": "Poverty; being trapped in a cycle of endless,fruitless toil."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 8,
    "name": "Lord of Staves: The Warden",
    "role": "The Pillar",
    "progression": "Social",
    "represents": "The Protector",
    "astral": "Stewardship; guarding the resources for future generations.",
    "umbral": "The Hoarder; guarding wealth so fiercely no one can use it." },
  { "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 9,
    "name": "Lady of Staves: The Matron",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Natural Wisdom",
    "astral": "Fertility and growth; the wisdom of seasons and cycles.",
    "umbral": "Stagnation; refusing to let things die to make room for the new."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Possession",
    "class": "The Harvesters",
    "rank": 10,
    "name": "The Bole",
    "progression": "Divine",
    "partner_deities": ["Nophica", "Althyk"],
    "represents": "Foundation",
    "astral": "Nophica's Mercy: The abundance of life; physical health and growth.",
    "umbral": "Althyk's Weight: The gravity of time; the inevitable end of all mortal cycles and the gravity of history."
  },

  /* IRONS (Ice - Penitent - Resolution) */
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 1,
    "name": "First Iron: The Chill",
    "progression": "Mortal",
    "represents": "Reality Check",
    "astral": "A harsh but necessary truth; the first step to atonement.",
    "umbral": "Bitterness; a heart that freezes over at the first sign of pain."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 2,
    "name": "Second Iron: The Links",
    "progression": "Mortal",
    "represents": "Shared Burden",
    "astral": "Finding a companion in the snow; mutual survival.",
    "umbral": "Codependency; being shackled to another's failures."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 3,
    "name": "Third Iron: The Wall",
    "progression": "Mortal",
    "represents": "Boundary",
    "astral": "The shield of the Fury; setting cold,hard limits for safety.",
    "umbral": "Isolation; becoming unreachable; an ice-locked soul."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 4,
    "name": "Fourth Iron: The Shelter",
    "progression": "Mortal",
    "represents": "Hibernation",
    "astral": "Strategic retreat; waiting for the blizzard to pass.",
    "umbral": "Burnout; collapsing in the cold because you tried to run too far."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 5,
    "name": "Fifth Iron: The Absolution",
    "progression": "Mortal",
    "represents": "Freedom",
    "astral": "Breaking the chains of the past; earned forgiveness.",
    "umbral": "The Fugitive; running from justice without actually repenting."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 6,
    "name": "Sixth Iron: The Summit",
    "progression": "Mortal",
    "represents": "Ascent",
    "astral": "Absolute self-command; the view from the frozen peak.",
    "umbral": "Frigidity; a peak that is beautiful but uninhabitable for others."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 7,
    "name": "Knight of Irons: The Exile",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Outcast",
    "astral": "The search for a new truth; the pilgrim's long walk.",
    "umbral": "The Pariah; feeling shunned by all without knowing why."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 8,
    "name": "Lord of Irons: The Inquisitor",
    "role": "The Pillar",
    "progression": "Social",
    "represents": "Judicial Authority",
    "astral": "Integrity; the cold application of law for the greater good.",
    "umbral": "Cruelty; the enjoyment of punishment over rehabilitation."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 9,
    "name": "Lady of Irons: The Saint",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Purified Wisdom",
    "astral": "Sacrifice for a higher cause; absolute inner peace.",
    "umbral": "Martyr-complex; suffering needlessly to make others feel guilty."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Resolution",
    "class": "The Penitent",
    "rank": 10,
    "name": "The Spear",
    "progression": "Divine",
    "partner_deities": ["Halone", "Menphina"],
    "represents": "Resolution",
    "astral": "Halone's Fury: The heat of battle; active resolve to conquer adversity and protect.",
    "umbral": "Menphina's Love: The cold light of the moon; peace in solitude and devotion."
  },
  
  /* SCALES (Fire - Merchants - Volition) */
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 1,
    "name": "First Scale: The Ember",
    "progression": "Mortal",
    "represents": "Drive",
    "astral": "A sudden drive to create; the first flame.",
    "umbral": "Burnout; aimless passion that fades quickly."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 2,
    "name": "Second Scale: The Trade",
    "progression": "Mortal",
    "represents": "Exchange",
    "astral": "Fair dealing; adapting goals for mutual success.",
    "umbral": "Unfair deals; greed vs necessity."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 3,
    "name": "Third Scale: The Quality",
    "progression": "Mortal",
    "represents": "Craft",
    "astral": "Pride in work; earned reputation.",
    "umbral": "Cutting corners; shoddy willpower."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 4,
    "name": "Fourth Scale: The Ledger",
    "progression": "Mortal",
    "represents": "Balance Sheet",
    "astral": "Security; knowing your worth.",
    "umbral": "Hoarding; fear of reinvestment."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 5,
    "name": "Fifth Scale: The Loss",
    "progression": "Mortal",
    "represents": "Risk",
    "astral": "Learning through failure; tempering the soul.",
    "umbral": "Bankruptcy of spirit; social discord."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 6,
    "name": "Sixth Scale: The Ruby Road",
    "progression": "Mortal",
    "represents": "Wealth",
    "astral": "Material mastery; peak influence.",
    "umbral": "Gilded cage; obsession with status."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 7,
    "name": "Knight of Scales: The Peddler",
    "role": "The Agent",
    "progression": "Social",
    "represents": "The Agent",
    "astral": "Resourcefulness; adaptability.",
    "umbral": "Silver-tongued lies; lack of direction."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 8,
    "name": "Lord of Scales: The Magnate",
    "role": "The Pillar",
    "progression": "Social",
    "represents": "Structural Authority",
    "astral": "Generosity; building a better city.",
    "umbral": "Avarice; ruthlessness."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 9,
    "name": "Lady of Scales: The Matriarch",
    "role": "The Sovereignty",
    "progression": "Social",
    "represents": "Communal Wisdom",
    "astral": "Nurturing; warmth of the hearth.",
    "umbral": "Suffocating control; killing innovation."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Volition",
    "class": "The Merchants",
    "rank": 10,
    "name": "The Balance",
    "progression": "Divine",
    "partner_deities": ["Azeyma", "Nald'thal"],
    "represents": "Equilibrium",
    "astral": "Azeyma's Truth: The warmth of truth; Victory through honesty; shining a light on deeds to bring justice.",
    "umbral": "Nald'thal's Judgment: The cold cost of fate; the finality of the bridge to the afterworld."
  }
]

app.get('/api/cards', (req, res) =>  {
  res.json({ cards });
});

module.exports = app;
module.exports.handler = ServerlessHttp(app);

//For testing locally
app.listen(3000, () => {
  console.log(`API running on http://localhost:3000`);
})