const express = require('express');
const cors = require('cors');
const ServerlessHttp = require('serverless-http');
const app = express();
app.use(cors());

//Deck of Sixty API
//Version 2.2
//Change Notes: All suits have been refactored to better align with their element and partner dieties. Major updates to "represents" descriptions, "role" designations for social tier cards, and astral and umbral interpretations across all suits.

const cards = [
  /* CROWNS (Lightning - Architects - Ingenuity) */
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 1,
    "name": "First Crown: The Spark",
    "progression": "Mortal",
    "represents": "Potential / Kinetic Energy",
    "astral": "A sudden bolt of insight; the raw energy required to begin a massive undertaking.",
    "umbral": "Unguided power; a bolt that causes damage because it has no circuit to follow."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 2,
    "name": "Second Crown: The Rivalry",
    "progression": "Mortal",
    "represents": "Ambition",
    "astral": "A \"race to the sky\"; healthy competition that forces one to refine their own methods.",
    "umbral": "Innovation curdled by spite; wasting energy on undermining another's foundation."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 3,
    "name": "Third Crown: The Foundation",
    "progression": "Mortal",
    "represents": "Integrity",
    "astral": "Building on solid ground; the establishment of proven, just rules that ensure success.",
    "umbral": "Bureaucratic gridlock; using \"the old ways\" or rigid rules to stifle new, brilliant ideas."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 4,
    "name": "Fourth Crown: The Monument",
    "progression": "Mortal",
    "represents": "Legacy",
    "astral": "A well-earned reputation; the security of knowing your work stands as a testament to your skill.",
    "umbral": "Resting on laurels; using past successes to justify present laziness or \"gatekeeping\" the craft."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 5,
    "name": "Fifth Crown: The Strike",
    "progression": "Mortal",
    "represents": "Deconstruction",
    "astral": "The \"Cleansing Storm.\" Breaking down an obsolete or corrupt idea to ensure the next one is stronger.",
    "umbral": "Ruin; a collapse caused by arrogance or refusing to acknowledge structural flaws."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 6,
    "name": "Sixth Crown: The Masterwork",
    "progression": "Mortal",
    "represents": "Completion",
    "astral": "The pinnacle of ingenuity; a design realized in its most perfect form. It suggests a time of harmony where the vision and the reality are one.",
    "umbral": "The \"empty shell\"; a beautiful facade with no purpose or soul. Building something impressive just for the sake of vanity, leaving the creator hollow."
  },
  { "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 7,
    "name": "Knight of Crowns: The Apprentice",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "Apprenticeship",
    "astral": "Diligent study of the craft; the hunger to learn from a master.",
    "umbral": "The \"Arrogant Novice\"; believing one's raw talent replaces the need for foundational study."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 8,
    "name": "Lord of Crowns: The Masterwright",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "Directorship",
    "astral": "Disciplined leadership; tempering like steel to ensure excellence.",
    "umbral": "Cruelty; breaking the tools through excessive pressure or impossible standards."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 9,
    "name": "Lady of Crowns: The Innovator",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Innovation",
    "astral": "Refined brilliance; the ability to see the \"spirit\" of a structure and how it serves the people.",
    "umbral": "The \"Gilded Dreamer\"; losing touch with reality in favor of impossible, over-complex designs that cannot be built."
  },
  {
    "suit": "Crowns",
    "element": "Lightning",
    "faculty": "Ingenuity",
    "class": "The Architects",
    "rank": 10,
    "name": "The Spire",
    "progression": "Divine",
    "partner_deities": ["Byregot","Rhalgr"],
    "represents": "Purification",
    "astral": "Byregot's Touch: Sudden architectural genius; a path forward where none existed; inspiration to build or repair.",
    "umbral": "Rhalgr's Wrath: The destruction of the old; the cleansing fire of a storm, making way for the new."
  },

  /* SWORDS (Wind - Pathfinders - Exploration) */
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 1,
    "name": "First Sword: The Breeze",
    "progression": "Mortal",
    "represents": "Initiative",
    "astral": "A sudden shift in the wind; the clarity and courage to take the first step toward the unknown.",
    "umbral": "Scattered thoughts; mental chaos or \"chasing the wind\" without a compass or destination."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 2,
    "name": "Second Sword: The Scout",
    "progression": "Mortal",
    "represents": "Observation",
    "astral": "Preparedness; gathering information before making a move.",
    "umbral": "Indecision; paralysis by analysis; being so overwhelmed by the vastness of the horizon that you fail to move at all."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 3,
    "name": "Third Sword: The Chart",
    "progression": "Mortal",
    "represents": "Strategy",
    "astral": "Mental discipline; mastery of one's environment through observation and data; having a clear, disciplined plan for the journey ahead.",
    "umbral": "Rigid mapping; clinging to the \"plan\" even when the actual winds have shifted."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 4,
    "name": "Fourth Sword: The Anchorage",
    "progression": "Mortal",
    "represents": "Preparation",
    "astral": "Strategic recovery; knowing when to lower the sails to repair the ship and soul before a major crossing.",
    "umbral": "Stagnation; avoiding conflict through apathy; fearing the open sea so much you never leave the docks."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 5,
    "name": "Fifth Sword: The Squall",
    "progression": "Mortal",
    "represents": "Adversity",
    "astral": "Growth through turbulence; using the \"headwinds\" of life to learn how to tack and maneuver.",
    "umbral": "Being \"lost at sea\"; allowing a temporary crisis to blow you completely off course or lose all momentum entirely."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 6,
    "name": "Sixth Sword: The Discovery",
    "progression": "Mortal",
    "represents": "Achievement",
    "astral": "The triumph of logic and skill; achieving a long-term goal; the successful conclusion of a voyage where the destination is finally reached.",
    "umbral": "Empty success; a win that leaves one isolated or hated; reaching a destination only to realize you’ve lost the joy of the journey itself."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 7,
    "name": "Knight of Swords: The Ranger",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "The Scout",
    "astral": "Relentless curiosity; the one who explores the unknown first.",
    "umbral": "Recklessness; wandering without a map or purpose; wandering so deep into the wilds that you lose your connection to the people you serve."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 8,
    "name": "Lord of Swords: The Captain",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "Martial Command",
    "astral": "Bravery or decisive leadership; the courage to stand by one's convictions; the courage to steer through the storm while holding the crew together.",
    "umbral": "Brutality; The \"Tyrant of the Tides\"; demanding total obedience while steering the ship toward personal glory."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 9,
    "name": "Lady of Swords: The Navigator",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Tactical Wisdom",
    "astral": "Foresight; seeing the 'long game' and guiding others toward it.",
    "umbral": "Treachery; using brilliant intellect for selfish or harmful ends."
  },
  {
    "suit": "Swords",
    "element": "Wind",
    "faculty": "Exploration",
    "class": "The Pathfinders",
    "rank": 10,
    "name": "The Arrow",
    "progression": "Divine",
    "partner_deities": ["Oschon", "Llymlaen"],
    "represents": "Destiny",
    "astral": "Oschon's Way: Finding your true path; the joy of movement and freedom.",
    "umbral": "Llymlaen's Tide: The relentless tide; the hard discipline of staying the course."
  },

  /* VESSELS (Water - Scholars - Insight) */
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 1,
    "name": "First Vessel: The Drop",
    "progression": "Mortal",
    "represents": "Curiousity",
    "astral": "The spark of intellectual or spiritual hunger; curiousity and the cognitive potential of it.",
    "umbral": "Emotional overwhelm; a leak of energy without a container to hold it."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 2,
    "name": "Second Vessel: The Thread",
    "progression": "Mortal",
    "represents": "Connection",
    "astral": "Identifying the hidden links between people or events; deep connection; a moment of perfect synchronicity.",
    "umbral": "Projection; seeing patterns that aren't there or confusing your own bias for fate."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 3,
    "name": "Third Vessel: The Wellspring",
    "progression": "Mortal",
    "represents": "Generosity",
    "astral": "Abundant expression; the joy of teaching and sharing wisdom with those who seek it.",
    "umbral": "Guardedness; hoarding knowledge or emotions out of fear, selfishness, or power."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 4,
    "name": "Fourth Vessel: The Basin",
    "progression": "Mortal",
    "represents": "Meditation",
    "astral": "The stillness of the mind; Mental and emotional clarity; the stillness required to hear the whispers of the star.",
    "umbral": "Stagnation; being caught in a loop of past memories, unable to let the water flow."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 5,
    "name": "Fifth Vessel: The Overflow",
    "progression": "Mortal",
    "represents": "Revelation",
    "astral": "A necessary cry; purging old grief to find a fresh flow; the emotional release that follows a long-held secret being told.",
    "umbral": "Drowning; losing oneself in an ocean of sadness or chaos; being swept away by a sudden flood of information or grief you weren't prepared for."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 6,
    "name": "Sixth Vessel: The Sea",
    "progression": "Mortal",
    "represents": "Integration",
    "astral": "Spiritual mastery; the realization that all knowledge and memory return to the same source.",
    "umbral": "Drifting; losing your individual purpose in the \"wider world\"; losing the sense of self."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 7,
    "name": "Knight of Vessels: The Acolyte",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "The Student",
    "astral": "The dedicated student; one who seeks a master or a new mystery to solve with humility.",
    "umbral": "The \"Echo-Chamber\"; repeating the words of others without understanding their true meaning."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 8,
    "name": "Lord of Vessels: The Archon",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "Intellectual Mastery",
    "astral": "Objective authority; the ability to categorize the world's mysteries and explain them clearly.",
    "umbral": "Intellectual Arrogance; believing that \"knowing the name of a thing\" is the same as understanding its soul."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 9,
    "name": "Lady of Vessels: The Oracle",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Intuitive Mastery",
    "astral": "Divine Insight; acting as a bridge between the mortal mind and the celestial patterns.",
    "umbral": "Delusion; getting lost in your own visions or using \"prophecy\" to manipulate the fate of others."
  },
  {
    "suit": "Vessels",
    "element": "Water",
    "faculty": "Insight",
    "class": "The Scholars",
    "rank": 10,
    "name": "The Ewer",
    "progression": "Divine",
    "partner_deities": ["Thaliak", "Nymeia"],
    "represents": "Continuity",
    "astral": "Thaliak's Stream: The flow of the river of knowledge; clarity and logical growth; the active pursuit of wisdom.",
    "umbral": "Nymeia's Thread: The Spinner's fate; accepting things that are beyond control; the passive mysterious influence of the celestial."
  },

  /* STAVES (Earth - Harvesters - Stewardship) */
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 1,
    "name": "First Staff: The Seed",
    "progression": "Mortal",
    "represents": "Potential",
    "astral": "The physical start of a long-term goal; laying the groudwork for later successes; nurtuting the soil for later harvest.",
    "umbral": "Waste; a valuable resource or talent that is left in the dark to rot instead of being planted."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 2,
    "name": "Second Staff: The Sapling",
    "progression": "Mortal",
    "represents": "Resiliance",
    "astral": "Adapting your foundations as you grow; resilience; the strength found in being flexible.",
    "umbral": "Fragility; being easily snapped by the winds of change because you lack a support system."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 3,
    "name": "Third Staff: The Roots",
    "progression": "Mortal",
    "represents": "Stability",
    "astral": "A deep connection to history and tradition; building a life that is \"weather-proof\" because it is grounded.",
    "umbral": "Stubbornness; being so deeply rooted in the way things were that you cannot move when the soil turns sour."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 4,
    "name": "Fourth Staff: The Fence",
    "progression": "Mortal",
    "represents": "Boundaries",
    "astral": "Protecting what is yours; healthy limits for yourself and others; protecting your time, energy, and resources from those who would over-harvest them.",
    "umbral": "Exclusion; building walls that prevent growth or community."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 5,
    "name": "Fifth Staff: The Famine",
    "progression": "Mortal",
    "represents": "Endurance",
    "astral": "Survival through scarcity; finding strength in lack; the winter wisdom of knowing how to prune what is dead to save the living.",
    "umbral": "Decay; a spiritual or physical rot caused by neglect or refusing to address a \"parasite\" in your life."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 6,
    "name": "Sixth Staff: The Harvest",
    "progression": "Mortal",
    "represents": "Abundance",
    "astral": "The successful completion of a cycle; a wealth of experience or resources that can be shared with others.",
    "umbral": "Exploitation; taking more from the land or people than you give, leading to a hollow and unsustainable success."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 7,
    "name": "Knight of Staves: The Gatherer",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "The Laborer",
    "astral": "The joy of simple, physical labor; finding spiritual peace in being of the earth and providing for the hearth.",
    "umbral": "Toil; being trapped in a cycle of endless, back-breaking work that offers no growth or future."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 8,
    "name": "Lord of Staves: The Warden",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "The Protector",
    "astral": "Stewardship; guarding the resources for future generations; the firm hand that guides family or community.",
    "umbral": "The Hoarder; guarding wealth and resources so fiercely that they become useless and stagnant."
  },
  { "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 9,
    "name": "Lady of Staves: The Matron",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Natural Wisdom",
    "astral": "Fertility and growth; the wisdom of seasons and cycles; a leader who understands the \"Seasons of the Soul\" and guides others with nurturing authority..",
    "umbral": "The \"Choking Vine\"; a maternal or communal power that refuses to let others grow independent or move on."
  },
  {
    "suit": "Staves",
    "element": "Earth",
    "faculty": "Stewardship",
    "class": "The Harvesters",
    "rank": 10,
    "name": "The Bole",
    "progression": "Divine",
    "partner_deities": ["Nophica", "Althyk"],
    "represents": "Foundation",
    "astral": "Nophica's Mercy: The abundance of life; physical health and growth.",
    "umbral": "Althyk's Weight: The gravity of time; the inevitable end of all mortal cycles and the gravity of history."
  },

  /* IRONS (Ice - Devout - Devotion) */
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 1,
    "name": "First Iron: The Chill",
    "progression": "Mortal",
    "represents": "Sincerity",
    "astral": "A harsh but necessary moment of clarity; the \"frozen breath\" of truth that forces one to stop drifting and choose a path.",
    "umbral": "Bitterness; a heart that ices over to avoid feeling pain, leading to isolation."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 2,
    "name": "Second Iron: The Link",
    "progression": "Mortal",
    "represents": "Loyalty",
    "astral": "Finding a companion in the snow; the strength found in a companion; the hound to the hunter.",
    "umbral": "Codependency; being shackled to another's failures; staying in a toxic or stagnant situation purely out of a misplaced sense of duty."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 3,
    "name": "Third Iron: The Shield",
    "progression": "Mortal",
    "represents": "Discipline",
    "astral": "The aegis of the Fury; setting firm, healthy boundaries to protect your focus and your sanctuary.",
    "umbral": "Isolation; becoming unreachable; an ice-locked soul; becoming so defensive and walled-off that you can no longer receive warmth or help."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 4,
    "name": "Fourth Iron: The Vigil",
    "progression": "Mortal",
    "represents": "Patience",
    "astral": "Strategic stillness; the \"Vigil of Menphina.\" Having the faith to wait for the blizzard to pass without losing hope.",
    "umbral": "Burnout; collapsing in the snow because you refused to stop or seek shelter when the storm began."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 5,
    "name": "Fifth Iron: The Penance",
    "progression": "Mortal",
    "represents": "Atonement",
    "astral": "Breaking the chains of the past; earned forgiveness; the difficult process of burning away past mistakes to emerge purified and free.",
    "umbral": "The Martyr-complex; wallowing in guilt or suffering needlessly to prove your worth to others."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 6,
    "name": "Sixth Iron: The Ascent",
    "progression": "Mortal",
    "represents": "Self-mastery",
    "astral": "The peak of the mountain; reaching a state where external chaos no longer affects your inner peace.",
    "umbral": "The Lonely Peak; achieving success at the cost of every human connection, standing high but entirely alone."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 7,
    "name": "Knight of Irons: The Exile",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "The Outcast",
    "astral": "The search for a new truth; the pilgrim's long walk; an outcast who uses their solitude to find a deeper, more personal truth.",
    "umbral": "The Pariah; feeling shunned by society and sinking into a cycle of self-pity or resentment."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 8,
    "name": "Lord of Irons: The Inquisitor",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "Judicial Authority",
    "astral": "Integrity; the cold, impartial application of a code to ensure the community remains safe and just.",
    "umbral": "Cruelty; the enjoyment of punishment over rehabilitation; using the law as a weapon to punish rather than a shield to protect."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 9,
    "name": "Lady of Irons: The Saint",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Purified Wisdom",
    "astral": "Absolute Devotion; one who has sacrificed their ego to become a beacon of hope and warmth for others in the dark.",
    "umbral": "Delusion; believing your purity makes you superior to others, leading to a dangerous spiritual narcissism."
  },
  {
    "suit": "Irons",
    "element": "Ice",
    "faculty": "Devotion",
    "class": "The Devout",
    "rank": 10,
    "name": "The Spear",
    "progression": "Divine",
    "partner_deities": ["Halone", "Menphina"],
    "represents": "Devotion",
    "astral": "Halone's Fury: The heat of battle; active resolve to conquer adversity and protect.",
    "umbral": "Menphina's Love: The cold light of the moon; peace in solitude and devotion."
  },
  
  /* SCALES (Fire - High-Traders - Judgment) */
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 1,
    "name": "First Scale: The Ember",
    "progression": "Mortal",
    "represents": "Drive",
    "astral": "A sudden drive to create or initiate; the desire to begin and the drive to see it through; the Morning Sun of a new venture.",
    "umbral": "Aimless passion; a fire that burns hot but has no fuel, leading to early burnout."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 2,
    "name": "Second Scale: The Trade",
    "progression": "Mortal",
    "represents": "Exchange",
    "astral": "Fair dealing; the wisdom to compromise and adapt for a win-win outcome.",
    "umbral": "The \"Bad Bargain\"; greed masquerading as necessity, leading to broken trust."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 3,
    "name": "Third Scale: The Quality",
    "progression": "Mortal",
    "represents": "Craft",
    "astral": "Earned reputation; the integrity of a masterwork that requires no defense; fair and quality interaction.",
    "umbral": "\"Gilded Dross\"; cutting corners or using shoddy materials while hoping the light doesn't reveal the cracks."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 4,
    "name": "Fourth Scale: The Ledger",
    "progression": "Mortal",
    "represents": "Balance",
    "astral": "Financial and spiritual security; the confidence of knowing exactly where you stand.",
    "umbral": "Stagnant Wealth; hoarding resources out of a fear of the change, preventing new growth."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 5,
    "name": "Fifth Scale: The Loss",
    "progression": "Mortal",
    "represents": "Risk",
    "astral": "Learning through failure; tempering the soul; finding the silver lining in a failure and using it to build a stronger foundation.",
    "umbral": "Spiritual Bankruptcy; social discord and bitterness caused by a refusal to accept a necessary loss."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 6,
    "name": "Sixth Scale: The Ruby Road",
    "progression": "Mortal",
    "represents": "Wealth",
    "astral": "Material mastery; peak influence; the ability to command the \"Market of Life\" with grace and wisdom.",
    "umbral": "The Gilded Cage; becoming a slave to your own status or becoming obsessed with the Price of everything while knowing the Value of nothing."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 7,
    "name": "Knight of Scales: The Peddler",
    "role": "The Envoy",
    "progression": "Social",
    "represents": "Opportunity",
    "astral": "Resourcefulness; the thrifty traveler who can find an opportunity in any desert.",
    "umbral": "Silver-tongued lies; the snake-oil salesman."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 8,
    "name": "Lord of Scales: The Magnate",
    "role": "The Guardian",
    "progression": "Social",
    "represents": "Structural Authority",
    "astral": "Philanthropy; using massive wealth to build the city for the benefit of all.",
    "umbral": "Avarice; a ruthless monopoly that crushes the embers of others to stay at the top."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 9,
    "name": "Lady of Scales: The Matriarch",
    "role": "The Sovereign",
    "progression": "Social",
    "represents": "Communal Wisdom",
    "astral": "The Hearth-Fire; nurturing communal growth and guarding the wealth of the family",
    "umbral": "The \"Smothering Flame\"; protecting the status quo so fiercely that you kill any chance for innovation."
  },
  {
    "suit": "Scales",
    "element": "Fire",
    "faculty": "Judgment",
    "class": "The High-Traders",
    "rank": 10,
    "name": "The Balance",
    "progression": "Divine",
    "partner_deities": ["Azeyma", "Nald'thal"],
    "represents": "Equilibrium",
    "astral": "Azeyma's Truth: The warmth of truth; Victory through honesty; shining a light on deeds to bring justice.",
    "umbral": "Nald'thal's Judgment: The cold cost of fate; the finality of the bridge to the afterworld."
  }
]

app.get('/api/cards', (req, res) =>  {
  res.json({ cards });
});

module.exports = app;
module.exports.handler = ServerlessHttp(app);

//For testing locally
app.listen(3000, () => {
  console.log(`API running on http://localhost:3000`);
})